import Head from 'next/head'
import React from 'react'
import styles from '@/styles/index.module.css'
import { Navbar } from '@/components/_navbar'
import { HomeContainer } from '@/components/_homeContainer'

export default function Homepage() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Navbar />
        <HomeContainer />
      </main>
    </>
  );
}